import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import map from 'lodash/map';

import Card from '../components/card';
import DisplayMessage from '../components/displayMessage';
import SearchBar from '../components/searchBar';
import { APIProps } from '../types/meteoData';

export default function Home() {
  const [searchData, setSearchData] = useState<APIProps | undefined>(undefined);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<null | string>(null);
  const [allCities, setAllCities] = useState<APIProps[]>([]);

  useEffect(() => {
    setAllCities(JSON.parse(localStorage.getItem('city') || '[]'));
  }, []);

  const handleSetAllCities = (cities: APIProps[]) => {
    setAllCities(cities);
    localStorage.setItem('city', JSON.stringify(cities));
  };

  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex flex-col justify-center h-screen items-center bg-embie-blue-light-300'>
        <h1 className='text-4xl font bold text-black'> Weather Forecast ☀️ </h1>
        <div className='h-5/6 w-10/12 md:w-6/12 flex flex-col border-black items-center bg-gray-200 border-4 rounded-lg'>
          <SearchBar
            setError={setError}
            setSearchData={setSearchData}
            setIsLoading={setIsLoading}
          />
          {!error && !searchData && (
            <DisplayMessage message='Enter a city name !' />
          )}
          {error && !searchData && <DisplayMessage message={error} />}
          {isLoading && <DisplayMessage message='Loading...' />}

          {searchData && (
            <Card
              city={searchData}
              allCities={allCities}
              setAllCities={handleSetAllCities}
            />
          )}
          <div className='w-full border-t-4 border-black my-3 flex flex-col items-center justify-center py-2'>
            {/* <DisplayMessage message='Registered cities ' /> */}

            {allCities.length == 0 && (
              <DisplayMessage message='No cities registered yet' />
            )}
            {allCities.length > 0 &&
              map(allCities, (city) => (
                <div
                  key={city.id}
                  className='flex flex-col w-full items-center py-1'
                >
                  <Card
                    city={city}
                    allCities={allCities}
                    setAllCities={handleSetAllCities}
                  />
                </div>
              ))}
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
