import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';

import Card from '../components/card';
import SearchBar from '../components/searchBar';
import { APIProps, Coords } from '../types/meteoData';

export default function Home() {
  const [meteoData, setMeteoData] = useState<APIProps | undefined>(undefined);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<null | string>(null);
  // const [coords, setCoords] = useState<Coords | undefined>(undefined);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex flex-col justify-center h-screen items-center'>
        <h1 className='text-4xl font bold'> Weather App</h1>
        <div className='h-5/6 w-6/12 border flex flex-col border-black items-center '>
          <SearchBar
            /* setCoords={setCoords} */ setError={setError}
            setMeteoData={setMeteoData}
            setIsLoading={setIsLoading}
          />
          {error && <p> {`${error}`}</p>}
          {isLoading && <p>I am loading</p>}
          {meteoData && <Card meteoData={meteoData} />}
          {/* {
            <GetData
              setMeteoData={setMeteoData}
              setIsLoading={setIsLoading}
              setError={setError}
              coords={coords}
            />
          } */}
          {/* <GetData /> */}
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
